export const rolePermissions = {
  superAdmin: [], // full access, skip all checks in ProtectedRoute

  admin: [
    "view_users",
    "edit_users",
    "delete_users",
    "manage_vendors",
    "view_vendors",
    "add_vendor",
    "edit_vendor",
    "delete_vendor",
    "manage_categories",
    "view_products",
    "add_products",
    "edit_products",
    "delete_products",
    "bulk_product_upload",
    "manage_auctions",
    "view_auctions",
    "view_orders",
    "order_management",
    "view_coupons",
    "create_coupons",
    "edit_coupons",
    "delete_coupons",
    "manage_coupons",
    "view_finance",
    "edit_finance",
    "view_invoices",
    "create_invoice_user",
    "create_invoice_vendor",
    "edit_invoices",
    "delete_invoices",
    "view_transactions",
    "send_notifications",
    "view_reports",
    "manage_discounts",
    "view_audit_logs",
    "export_settings",
    "system_settings",
    "access_api",
    "manage_integrations",
    "view_system_health",
    "manage_backups",
    "view_activity_logs",
    "manage_webhooks",
    "configure_security",
    "manage_themes",
    "customize_ui",
    "manage_workflows",
    "manage_app",
  ],

  "auction-manager": ["manage_auctions", "view_auctions", "view_reports"],

  "finance-manager": [
    "view_orders",
    "order_management",
    "view_finance",
    "edit_finance",
    "view_invoices",
    "view_reports",
    "view_transactions",
  ],

  vendor: [
    "view_products",
    "add_products",
    "delete_products",
    "bulk_product_upload",
    "view_reports",
    "view_orders",
    "order_management",
    "view_auctions",
  ],

  support: ["support_actions", "view_users", "view_products", "view_orders"],

  user: [],
};
